//todo: gradient para colores de figma que escogi
//todo: border radius y asi maybe ig
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //overall class and shit
    <div className="min-h-screen flex flex-row justify-center items-center background">
        <div className="flex flex-col p-10 bg-white rounded-xl">
            {children}
        </div>
    </div>
  );
}
